version: 1.0.{build}
image:
  - Visual Studio 2017
environment:
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.13"
  PYTHON_ARCH: "32"
  matrix:
    - build_type: windows32
    - build_type: android_game12
    - build_type: android_lib


platform:
  - x86

configuration:
  - Release

before_build:
  - ps: ./tools/appveyor-scripts/before-build.ps1

build_script:
  - ps: ./tools/appveyor-scripts/build.ps1


clone_depth: 1

test: off
