matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      language: cpp
      sudo: required
      env: BUILD_TARGET=linux
    - os: osx
      language: cpp
      osx_image: xcode9.3
      sudo: required
      env: BUILD_TARGET=ios_build
    - os: linux
      language: cpp
      sudo: required
      env: BUILD_TARGET=android_lib_x86_64
    - os: linux
      language: cpp
      sudo: required
      env: BUILD_TARGET=android_game12
    - os: linux
      language: cpp
      sudo: required
      env: BUILD_TARGET=android_lib_armeabi_v7a
    - os: linux
      language: cpp
      sudo: required
      env: BUILD_TARGET=android_lib_x86
    - os: linux
      language: cpp
      sudo: required
      env: BUILD_TARGET=android_lib_arm64_v8a
    - os: osx
      language: cpp
      osx_image: xcode9.3
      sudo: required
      env: BUILD_TARGET=osx

script:
- tools/travis-scripts/run-script.sh
before_install:
- tools/travis-scripts/before-install.sh

cache:
  bundler: true
